Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,7 +15,9 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Install Required Tools
-        run: sudo apt-get update && sudo apt-get install -y mtools lzma fuse3
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y mtools lzma fuse3 libfuse2
 
       - name: Extract HDI File
         run: |
@@ -27,9 +29,11 @@ jobs:
           mkdir modified_hdi temp_mount
           for hdi in extracted_hdi/*.hdi; do
             hdi_name=$(basename "$hdi")
-            sudo mount -o loop "$hdi" temp_mount
+            # Try using fuse to mount HDI instead of standard mount
+            sudo mount -t auto -o loop "$hdi" temp_mount || (echo "Mount failed for $hdi" && dmesg)
+            # If mount is successful, copy files and unmount
             sudo cp -v *.XDF *.EXE temp_mount/
-            sudo umount temp_mount
+            sudo umount temp_mount || echo "Failed to unmount $hdi"
             cp "$hdi" "modified_hdi/$hdi_name"
           done
 
